# Generated by Django 5.2.9 on 2026-01-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContinuingEducationTeacherModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.CharField(max_length=4)),
                ("semester", models.IntegerField()),
                ("course_code", models.CharField(max_length=6)),
                ("document_type_id", models.IntegerField()),
                ("document_number", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "continuing_education_teachers",
                "unique_together": {
                    (
                        "year",
                        "semester",
                        "course_code",
                        "document_type_id",
                        "document_number",
                    )
                },
            },
        ),
    ]
