# Generated by Django 5.2.9 on 2026-01-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WellbeingHumanResourceModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.CharField(max_length=4)),
                ("semester", models.IntegerField()),
                ("activity_code", models.CharField(max_length=50)),
                ("organization_unit_code", models.CharField(max_length=50)),
                ("document_type_id", models.IntegerField()),
                ("document_number", models.CharField(max_length=50)),
                ("dedication", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "bienestar_recursos_humanos",
                "unique_together": {
                    (
                        "year",
                        "semester",
                        "activity_code",
                        "organization_unit_code",
                        "document_type_id",
                        "document_number",
                    )
                },
            },
        ),
    ]
