# Generated by Django 5.2.9 on 2026-01-23

import os

from django.db import migrations
from django.contrib.auth.hashers import make_password


def seed_root_role_and_user(apps, schema_editor):
    UserModel = apps.get_model("users", "UserModel")
    RoleModel = apps.get_model("users", "RoleModel")
    RolePermissionModel = apps.get_model("users", "RolePermissionModel")

    # 1) Ensure root role exists
    root_role, _ = RoleModel.objects.get_or_create(
        name="root",
        defaults={"description": "Administrador raiz (TI)"},
    )

    # 2) Ensure root has full permissions for all known modules
    for module in ("courses", "wellbeing", "continuing_education"):
        RolePermissionModel.objects.update_or_create(
            role=root_role,
            module=module,
            defaults={
                "can_view": True,
                "can_create": True,
                "can_edit": True,
                "can_delete": True,
            },
        )

    # 3) Seed root user (idempotent by email)
    email = os.getenv("ROOT_SEED_EMAIL", "root@snies.local").strip().lower()
    password = os.getenv("ROOT_SEED_PASSWORD", "root12345")
    name = os.getenv("ROOT_SEED_NAME", "Root Admin")

    # If already exists, do not recreate; just ensure it's root and privileged.
    user = UserModel.objects.filter(email=email).first()
    if user:
        update_fields = []
        if getattr(user, "role_id", None) != root_role.id:
            user.role_id = root_role.id
            update_fields.append("role")
        if not user.is_staff:
            user.is_staff = True
            update_fields.append("is_staff")
        if not user.is_superuser:
            user.is_superuser = True
            update_fields.append("is_superuser")
        if not user.is_active:
            user.is_active = True
            update_fields.append("is_active")
        if update_fields:
            user.save(update_fields=update_fields)
        return

    user = UserModel(email=email, name=name, is_staff=True, is_superuser=True, is_active=True)
    # Note: historical model instances in migrations may not expose set_password(),
    # so we hash explicitly.
    user.password = make_password(password)
    user.role_id = root_role.id
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rbac_roles_permissions"),
    ]

    operations = [
        migrations.RunPython(seed_root_role_and_user, reverse_code=migrations.RunPython.noop),
    ]

