# Generated by Django 5.2.9 on 2026-01-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_seed_root_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermissionmodel",
            name="module",
            field=models.CharField(
                choices=[
                    ("courses", "Cursos"),
                    ("wellbeing", "Bienestar"),
                    ("continuing_education", "Educación continua"),
                ],
                max_length=32,
            ),
        ),
    ]
