# Generated by Django 4.2.15 on 2026-01-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WellbeingActivityModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.CharField(max_length=4)),
                ("semester", models.IntegerField()),
                ("organization_unit_code", models.CharField(max_length=50)),
                ("activity_code", models.CharField(max_length=50)),
                ("activity_description", models.TextField()),
                ("wellbeing_activity_type_id", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("national_source_id", models.IntegerField()),
                (
                    "national_funding_value",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("funding_country_id", models.IntegerField()),
                (
                    "international_source_entity_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "international_funding_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
            ],
            options={
                "db_table": "actividades_bienestar",
            },
        ),
    ]
