# Generated by Django 5.2.9 on 2026-01-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContinuingEducationBeneficiaryModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.CharField(max_length=4)),
                ("semester", models.IntegerField()),
                ("course_code", models.CharField(max_length=6)),
                ("beneficiary_type_extension_id", models.IntegerField()),
                ("beneficiaries_count", models.IntegerField()),
            ],
            options={
                "db_table": "continuing_education_beneficiaries",
                "unique_together": {
                    ("year", "semester", "course_code", "beneficiary_type_extension_id")
                },
            },
        ),
    ]
