# Generated by Django 5.2.9 on 2026-01-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("user_id", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("module", models.CharField(blank=True, max_length=64, null=True)),
                ("action", models.CharField(blank=True, max_length=32, null=True)),
                ("resource_id", models.CharField(blank=True, max_length=64, null=True)),
                ("level", models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                "db_table": "notifications",
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_read", "created_at"],
                        name="notificatio_user_id_5cf777_idx",
                    )
                ],
            },
        ),
    ]
