# Generated by Django 4.2.15 on 2026-01-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WellbeingBeneficiaryActivityModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.CharField(max_length=4)),
                ("semester", models.IntegerField()),
                ("organization_unit_code", models.CharField(max_length=50)),
                ("activity_code", models.CharField(max_length=50)),
                ("beneficiary_type_id", models.IntegerField()),
                ("beneficiaries_count", models.IntegerField()),
            ],
            options={
                "db_table": "actividad_bienestar_beneficiarios",
            },
        ),
    ]
