# Generated by Django 4.2.15 on 2026-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("software_activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwareactivitymodel",
            name="career",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
