# Generated by Django 5.2.9 on 2026-01-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLogModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=20)),
                ("method", models.CharField(max_length=10)),
                ("path", models.TextField()),
                ("status_code", models.IntegerField()),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("user_email", models.CharField(blank=True, max_length=254, null=True)),
                ("user_role", models.CharField(blank=True, max_length=50, null=True)),
                ("ip", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("view_name", models.CharField(blank=True, max_length=255, null=True)),
                ("module", models.CharField(blank=True, max_length=64, null=True)),
                ("resource_id", models.CharField(blank=True, max_length=64, null=True)),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_logs",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="audit_logs_created_262184_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="audit_logs_user_id_73c422_idx"
                    ),
                    models.Index(
                        fields=["module"], name="audit_logs_module_f52b4d_idx"
                    ),
                    models.Index(
                        fields=["action"], name="audit_logs_action_31f574_idx"
                    ),
                ],
            },
        ),
    ]
